version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.89.0
    steps:
      - checkout

      - run:
          name: Install Tarpaulin
          command: cargo install cargo-tarpaulin
          environment:
            RUSTFLAGS: --cfg procmacro2_semver_exempt

      - run:
          name: Generate coverage report
          command: cargo tarpaulin --out Xml

      - save_cache:
          key: cargo-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - target

      - codecov/upload:
          file: cobertura.xml
